environment:
  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "2.7"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  - appveyor DownloadFile https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.7.5-win-64.exe -FileName loner_conda.exe
  - set "CONDA_PKGS_DIRS=C:\condacache\pkgs"
  - set "CONDA_ALWAYS_YES=true"
  - set "CONDA_AUTO_UPDATE_CONDA=false"
  - loner_conda.exe create -p C:\test_conda python=%PYTHON_VERSION% conda conda-build pytest six pytest-cov pytest-mock=1 "conda-package-handling!=1.5.0"
  # these correspond to folder naming of miniconda installs on appveyor.  See
  # https://www.appveyor.com/docs/installed-software#python
  - call "C:\test_conda\Scripts\activate.bat"

  # Needed for building python2.7 x64 extensions with conda-build
  - conda install -c defaults -c conda-forge vs2008_express_vc_python_patch
  - call setup_x64

  - conda info
  # this is to ensure dependencies
  - conda build conda.recipe --no-test
  - conda install --use-local conda-package-handling

# Not a .NET project, we build package in the install step instead
build: false

test_script:
  # rebuilding the recipe with our new CPH installed tests the unicode issue that occurred in 1.5.0
  - conda build conda.recipe
  - py.test --color=yes -v --cov conda_package_handling --cov-report xml tests

on_success:
  - conda install codecov
  - codecov --env PYTHON_VERSION --file C:\projects\conda-package-handling\coverage.xml
